### PR TITLE
Tests for white space handling

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [ ] [4.4:54](http://dev.pef-format.org/dp2/index.xhtml#4.4:54)
- [x] [4.4:55](http://dev.pef-format.org/dp2/index.xhtml#4.4:55)

Related issues:
- [x] https://github.com/snaekobbi/pipeline-mod-braille/pull/2
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/30
- [ ] [obfl#25](https://github.com/joeha480/obfl/issues/25)

### CODE REVIEW

**Comment by bertfrees** [comment]
@mixa72 I added your last example here: http://dev.pef-format.org/dp2/white-space/test/white-space/test.xprocspec.xhtml#55.2. I solved this by adding a non-breaking space and a zero-width space (`&#x00A0;&#x200B;`) before and a non-breaking space (`&#x00A0;`) after the expression. The zero-width space will prevent that the expression is preceded by a space when it appears at the beginning of a line.

I hope I understand the requirement right?

We could also have a solution where you don't have to insert the special spaces manually. Then you would mark up the mathematical expressions with some class (or brl:class) and the script would take care of the rest.

I'm not sure yet how we should handle the `brl:literal`. If the literal braille were Unicode braille, it would be straightforward, but if it has to be ASCII braille it becomes slightly more difficult.

Could you perhaps make a new requirement (new github issue) for this? Because it's not directly related to white space handling.

**Comment by mixa72** [comment]
I think it's no problem if we have to use Unicode braille in brl:literal (brl:literal is only a fallback and not used very often).

Remember that the mathematical expression should NEVER appear at the beginning or end of a line. When this happens, we use a sequence of 2 non-breaking spaces to "glue" it to the preceding or following word:

Example:
<pre>
BLA  MATH  BLA BLA BLA (ok)
BLA BLA BLA  MATH  BLA (ok)
MATH  BLA BLA BLA BLA (not allowed)
BLA BLA BLA BLA  MATH (not allowed)
</pre>

I'm not sure if I understand right how the zero-width space works, but if it can achieve the above mentioned results, then it's fine.

**Comment by bertfrees** [comment]
OK, if math is never allowed at the beginning or end of lines, then the solution is indeed to use two non-breaking spaces before and after the expression and no other space. We don't need a zero-width space in this case.

A [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) is just like a normal space in that it creates a soft wrap opportunity (a line can break there), but it is invisible.

When you decide brl:literal with ASCII braille is a requirement, just create a new issue for it. It's not such a big deal to implement.

**Comment by bertfrees** [comment]
@snaekobbi/experts Please have a look at http://dev.pef-format.org/dp2/white-space/index.xhtml and let me know if you think something w.r.t. requirements for white space handing is not clear enough, something is missing, or if you don't agree with a requirement.

**Comment by bertfrees** [comment]
Added an example from Kari for requirement 45 in commit https://github.com/snaekobbi/requirements/commit/e47078bf92f0674c09aa777c83921a31c2cb16cc

**Pull request merged**
