### PR TITLE
Tests for indication of original pagination

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [ ] [4.7:102](http://snaekobbi.github.io/requirements#4.7:102)
- [x] [4.8:105](http://snaekobbi.github.io/requirements#4.8:105)
- [x] [4.8:106](http://snaekobbi.github.io/requirements#4.8:106)
- [ ] [4.8:107](http://snaekobbi.github.io/requirements#4.8:107)

Related issues:
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/14
- [ ] https://github.com/snaekobbi/pipeline-mod-braille/issues/23

### CODE REVIEW

**Comment by bertfrees** [comment]
@KariRudjord Next up are print page breaks.

You already provided an example of indicating print page breaks as marks in the left margin (requirement [4.8:106](http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:106)). Is this always a mark on a separate line? Or can it be on the same line as other text. The example you gave has a `pagenum` element inside a `level2`. Can it also appear inside a `p` for example, and what happens in that case?

Any examples of requirements [4.8:105](http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:105) and [4.8:107](http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:107)?

**Comment by KariRudjord** [comment]
@bertfrees print page breaks: yes, marks in the left margin can be on the same line as other text. 
Yes, the pagenum can also appear inside a <p>. Then the mark in the margin appear at the same line as the word that comes after the <pagenum>-tag.

**Comment by bertfrees** [comment]
Ok. Do you have an example of that?

Could the others @snaekobbi/expert-group help out for requirements [4.8:105](http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:105) (full lines across the width of the page) and [4.8:107](http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:107) (skipping page breaks indication in some cases)?

**Comment by dkager** [comment]
Here is what Dedicon does:

* Print page numbers are centered at the top of the page.
* Braille page numbers are right-aligned at the top of the page.
* If one braille page contains content from multiple print pages, both print page numbers appear in the top center position.
* If the page numbers don't fit on one line , they are continued on the next.
* For some categories of books, at the position of the page break, the new print page number is inserted, centered with a line of whitespace above and below.

Do the current requirements cover this? Most notably, putting both print page numbers at the top.

Will try and get some test data.

**Comment by bertfrees** [comment]
Thanks Davy.

**Comment by mixa72** [comment]
Hi Bert,

Please find attached an example of 4.8:105 / 4.8:107. 
However, we don't use this layout yet, but would like to be 
able to do so in the future. It's only a draft, but quite 
similar to the layout used in some French speaking countries.

Regards,
Mischa

Am 08.06.2015 um 15:27 schrieb Bert Frees:
> Ok. Do you have an example of that?
>
> Could the others @snaekobbi/expert-group
> <https://github.com/orgs/snaekobbi/teams/expert-group> help
> out for requirements 4.8:105
> <http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:105>
> (full lines across the width of the page) and 4.8:107
> <http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.8:107>
> (skipping page breaks indication in some cases)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snaekobbi/requirements/pull/36#issuecomment-109995659>.
>

-- 
Mischa Künzle
Medienverlag
Blindenschrift

SBS Schweizerische Bibliothek für Blinde,
Seh- und Lesebehinderte
Grubenstrasse 12
CH-8045 Zürich
Fon +41 43 333 32 32
Fax +41 43 333 32 33
mailto:mischa.kuenzle@sbs.ch
http://www.sbs.ch


-----
Tag der offenen Tuer - Die SBS mit allen Sinnen erleben
Die SBS laedt Sie herzlich ein: 27. Juni 2015 von 9 bis 16 Uhr. 
Mehr Informationen erhalten Sie unter http://www.sbs.ch/offenetuer
p
             XYZ
             ---

   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 -----------------------_#AB
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA      #A
pBLA BLA BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 -----------------------_#AC
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA      #B
pBLA BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 -----------------------_#AD
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 -----------------------_#AE
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA    #C
pBLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 -----------------------_#AF
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA    #D
pBLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 ------------------_#AG-_#AI
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.



                          #E
p
p


source code:

<pagenum id="page-11" page="normal">11</pagenum>
<h1>xyz</h1>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<pagenum id="page-12" page="normal">12</pagenum>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<pagenum id="page-13" page="normal">13</pagenum>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<pagenum id="page-14" page="normal">14</pagenum>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<pagenum id="page-15" page="normal">15</pagenum>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<pagenum id="page-16" page="normal">16</pagenum>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<pagenum id="page-17" page="normal">17</pagenum>
<pagenum id="page-18" page="normal">18</pagenum>
<pagenum id="page-19" page="normal">19</pagenum>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>

**Comment by stesk** [comment]
Current practice at Nota, as far as I can work out, is the following:
* A page number between blocks is indicated by a full line of dashes terminated by the prefix s and then the page number in question.
* A page number within a block is extracted such that it appears immediately above the block, again as a line with the number at the end.
* On recto braille pages the range of print pages represented on that page is indicated in the middle of the footer alongside the right-aligned braille page number. (There are no footers on verso pages.)
The current implementation is somewhat buggy, and the feature is rarely used. Now that we have a chance to do it right, I should probably confer with some of my colleagues as to what that entails.

**Comment by stesk** [comment]
I should add that I can provide a PEF example of the current layout, but I'm not sure to what extent we actually want to preserve that.

**Comment by bertfrees** [comment]
@mixa72 Great!

@stesk Sure, we'll do it right now :)

**Comment by KariRudjord** [comment]
@bertfrees I've sent you an example of 4.8:106 inside a <p> by email.

**Comment by bertfrees** [comment]
Cool, thanks Kari.

**Comment by bertfrees** [comment]
@mixa72 wrote:
> Hi Bert,
> Please find attached two examples of downshifted print page numbers in the footer.

Thanks Mischa, added your example (see [4.7:102](http://dev.pef-format.org/dp2/print-pages/index.xhtml#4.7:102)). Maybe give it a bit more explanation? Because I think it's a typical thing for SBS and maybe others don't get it. The `_#AA,;` `_#AB,+` etc. may look a bit cryptic to some.

**Comment by mixa72** [comment]
Here is a short explanation of my examples in 4.7:102:
* the footer may appear either on right hand pages only (usually in fiction books) or both on left and right hand pages (in more complex books such as non-fiction or educational literature)
* the footer contains the range of print page numbers (left-aligned), a short information (heading/cue) about the current section (centered) and the braille page number (right-aligned)
* the range of print page numbers is preceded by the symbol '_' (dots 456; it's the symbol we generally use to reference print page numbers): _#AB,/ means from print page 12 to print page 14 (the second part of the number ,/ = 14 is a 'downshifted' number format which is also used for dates and ordinal numbers)
* if the print page numbers are omitted (or not available), the gap in the footer is filled with ':::' (left-aligned) followed immediately by the heading/cue information.
* if both print page numbers and heading/cue information is omitted, the text flows into the footer: a gap of at least 4 braille cells is required before the braille page number (right-aligned)..

**Comment by bertfrees** [comment]
Great

**Comment by bertfrees** [comment]
@dkager said
> Here is what Dedicon does:
> [...]
> * If one braille page contains content from multiple print pages, both print page numbers appear in the top center position.

Could I have an example of how this would look exactly?

> * If the page numbers don't fit on one line , they are continued on the next.

Could I have an example of how this would look exactly?

> * For some categories of books, at the position of the page break, the new print page number is inserted, centered with a line of whitespace above and below.

Q1: Is the pagenum taken out of the normal flow or not?
Q2: What happens if the print page break and braille page break coincide? I.e. if no text precedes or follows the pagenum on the same braille page?
Q2:

**Comment by dkager** [comment]
>> If one braille page contains content from multiple print pages, both print page numbers appear in the top center position.
> Could I have an example of how this would look exactly?
We use the very top row of the page. The number is centered, e.g. (using dots to represent spaces):
```
.......24.......
```
That's a page of width 16 cells. For two or more print page numbers we write them as a range:
```
.....24.-.25....
```
This is a simplification as the braille page number would also be printed in the top-right corner.

>> If the page numbers don't fit on one line, they are continued on the next.
> Could I have an example of how this would look exactly?
I'll ask for an example: I've never ran across one and think it unlikely that one will show up (you'd need very long page numbers).

>> For some categories of books, at the position of the page break, the new print page number is inserted, centered with a line of whitespace above and below.
> Q1: Is the pagenum taken out of the normal flow or not?
In what way?
> Q2: What happens if the print page break and braille page break coincide? I.e. if no text precedes or follows the pagenum on the same braille page?
No idea. My initial thoughts are that in this case the braille page really covers only one print page, so no page change indication is added and the page header lists only one print page number.

**Comment by bertfrees** [comment]
>> Q1: Is the pagenum taken out of the normal flow or not?
>
> In what way?

Example:
```xml
bla <pagenum>24</pagenum> bla bla bla bla
```
not taken out of flow:
```
bla

.......24.......

bla bla bla bla
```

or taken out of flow, meaning the current line is finished first:
```
bla bla bla bla

.......24.......

bla
```

> No idea. My initial thoughts are that in this case the braille page really covers only one print page, so no page change indication is added and the page header lists only one print page number.

Yes that is what I would think except I haven't seen an actual example of this yet although it seems like a fairly common thing to happen. I'm asking because this is the only feature that would make the print page break indicator something special. Otherwise it's just a simple block.

**Comment by dkager** [comment]
Q1:
The pagenum is probably not taken out of the normal flow. As with Q2 I have some difficulties finding out. I'll work on it.

Q2:
Doesn't this imply the print material contains a partially blank page, or a page with a large top or bottom margin? This sounds like a clear separation between levels (e.g. chapters) and would get the same behavior in braille. I haven't seen this in the sample books I looked at. I don't have direct access to the current conversion system yet but I'll forward this to the transcribers and come back to it.

**Comment by bertfrees** [comment]
It doesn't imply a partially blank page, but chances it happens are higher on a chapter change, because often at the start of chapter a new print page is started and also a new braille page.

**Comment by dkager** [comment]
Q1:
Confirmed, pagenums stay in the normal flow. Even if a pagenum occurs in the middle of a word I'm told.

**Pull request merged**
