### PR TITLE
Tests for double letter spacing

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [ ] [4.3:36](http://snaekobbi.github.io/requirements#4.3:36)

Related issues:
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/15
- [ ] https://github.com/snaekobbi/pipeline-mod-braille/issues/24

### CODE REVIEW

**Comment by jukkae** [comment]
We have two Braillo model 200's. We also print some of our material at Finnish Federation of the Visually Impaired. I'm not sure what printers they have, but all our files are fully compatible with their printers as well.

The *.cod files are the files we send to the printer. They are either [Braille ASCII](https://en.wikipedia.org/wiki/Braille_ASCII) or a slight variation thereof. Some tools produce alternative mappings for some characters; I've found alternative mappings for four characters and it's likely there are no more than those. The alternative mappings I've found are as follows:

Official | Alternative | Dots
---------|-------------|-----
 } | \] | 1-2-4-5-6
\\ | \| | 1-2-5-6
{ | \[ | 2-4-6
\~ | ^ | 4-5

The official and alternative versions are interchangeable, ie. when sent to the printer they both produce the same dot pattern. I have no idea where the alternative version originates or whether it or some other variation is used by anybody else.

As for DTBook examples and shorter examples in general, I'm working on it.

**Comment by bertfrees** [comment]
@jukkae Thanks. I noticed the .cod files contain both lowercase and uppercase letter. Can I assume they can be used interchangeably? Or do they represent different patterns? The uppercase letters seem to be used for numbers only.

The Braillo printers have the ability to select from a wide range of ASCII tables and even to edit the tables. The table that is called `BRAILLO-6-us-001-00` on your printer corresponds with your Wikipedia link (The North American Braille ASCII Code). It is implemented here: https://github.com/joeha480/brailleutils/blob/7270cde14bfd62a93b9d144a9a1b33d9e01c24a4/braille-utils.impl/src/com_braillo/BrailloTableProvider.java#L117.

Interesting is that your Braille printer also has a menu option for making a printout of ASCII tables. The printout will show all the different dot combinations for ASCII values from 0 to 255.

**Comment by jukkae** [comment]
Lowercase and uppercase letters can be used interchangeably, they represent - and are printed as - the same dot patterns.

I didn't know that printing out the ASCII tables is possible, thanks. I'll do that tomorrow and see what comes up.

**Comment by jukkae** [comment]
Right, I've got it.

We currently have the ASCII table setting set to USA Braille ASCII and that is what we supposedly use. However, Braille ASCII only specifies code points 20 - 5F, even though the range of all printable ASCII characters extends to 7E. Printable code points outside the Braille ASCII standard, that is, 60 - 7E, correspond to the characters in the range 40 - 5E. Because of this, capitals and minuscules are interchangeable (e.g. A = 41 while a = 61). Also, because of this, aforementioned character pairs are interchangeable (e.g. [ = 5B and { = 7B). There's 5 of these character pairs in total, I updated the table above.

**Comment by bertfrees** [comment]
Thanks very much! I should know enough now to move on.

**Comment by bertfrees** [comment]
@joeha480 Braille Utils should be able to do this, right?

**Comment by dkager** [comment]
Is [this script](http://www.daisy.org/projects/pipeline/doc/scripts/EmbossPEF.html) related? Also, we use Braillo 650 SF.

**Comment by bertfrees** [comment]
Yes, this script was written by Joel for Pipeline 1. I use the same library in my *-to-pef scripts to produce braille output in BRF format. And I also use it for converting test data in BRF format to PEF. It shouldn't be very hard to add support for the Braillo 650 SF.

**Comment by joeha480** [comment]
@bertfrees Braille Utils should be able to do what? Support Braillo 650 SF?

**Comment by bertfrees** [comment]
@joeha480 I mean to have an table in which the characters in the range 60 - 7E corresponds to the characters in range 40 - 5E (for text2pef).

**Comment by joeha480** [comment]
@bertfrees if you mean that several different characters should map to the same braille pattern then that's not really supported at the moment, but we could look into that. Probably not a big problem.

**Pull request merged**
