### PR TITLE
Tests for horizontal positioning and leaders

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [x] [4.4:65](http://snaekobbi.github.io/requirements#4.4:65)

Related issues:
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/21
- [ ] https://github.com/snaekobbi/pipeline-mod-braille/issues/17

### CODE REVIEW

**Comment by mixa72** [comment]
Another use case (with more than two columns) would be the creation of tables in matrix-layout. But as you can hardly predict column width before the translation, we usually arrange them manually after the translation (in the "intermediate format"). Moreover, there is already a dedicated mark-up element to deal with tables (table, tr, td, etc.) so that we can drop this use case. I don't think that there's another one besides the one I sent you.
As to the mark-up I consider <code>li</code> elements with <code>lic</code> inside a good solution.

**Comment by bertfrees** [comment]
It's not entirely clear to me yet if we should handle horizontal positioning and tables the same way. They are very related for sure. But anyway we'll cover tables in matrix layout in https://github.com/snaekobbi/requirements/issues/18.

**Comment by bertfrees** [comment]
@snaekobbi/experts Please have a look at http://dev.pef-format.org/dp2/horizontal-pos/index.xhtml and let me know if you think something w.r.t. requirements for horizontal positioning and leaders is not clear enough, something is missing, or if you don't agree with a requirement.

**Comment by bertfrees** [comment]
Closing because merged into tables: https://github.com/snaekobbi/requirements/pull/18

**Pull request closed without merging**
