### PR TITLE
Tests for line spacing

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [x] [4.4:74](http://snaekobbi.github.io/requirements#4.4:74)
- [x] [4.4:75](http://snaekobbi.github.io/requirements#4.4:75)
- [x] <del>[4.4:76](http://snaekobbi.github.io/requirements#4.4:76)</del>

Related issues:
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/18
- [ ] https://github.com/snaekobbi/pipeline-mod-braille/issues/26

### CODE REVIEW

**Comment by bertfrees** [comment]
Same comment about test granularity as in #6. The test covers not only line spacing but also translation, layout of page numbers, etc. And there is a special marker at the left margin before the second paragraph. Is that to indicate a print page number? These features should be tested separately.

**Comment by bertfrees** [comment]
@KariRudjord You already provided an example of single and double line spacing (requirement [4.4:74](http://dev.pef-format.org/dp2/line-spacing/index.xhtml#4.4:74)). Thanks for that.

Are there any special requirements regarding line spacing when printing double-sided, such as alternating lines on odd and even pages (requirement [4.4:75](http://dev.pef-format.org/dp2/line-spacing/index.xhtml#4.4:75))? Something that is not explicitly mentioned in the requirements but that I remember we talked about is that when alternating lines, the headers and footers might still need to overlap.

NLB also explicitly requested the possibility to have a line spacing somewhere between single and double (requirement [4.4:76](http://dev.pef-format.org/dp2/line-spacing/index.xhtml#4.4:76)). Do you have some examples for that as well?

Is there a requirement from your side to change the line spacing on a finer level than document level? For example, could the line spacing vary per section, page, or paragraph? Or is it enough if line spacing can be configured for the whole document?

**Comment by KariRudjord** [comment]
@bertfrees Regarding line spacing when printing double-sided, we don't have any special requirements. Alternating lines is not how we print it today, so I can not give you any example. If no one else need this feature, we can just let it go and have overlapping lines.

About the possibility to have a line spacing somewhere between single and double: we don't do this today, so I can not give any example. I have checked around, and this is not an important feature for us. Since noone else need it, let it go. It is not importent enough to bother about.

About changing line spacing on a finer level than document: no need for this in NLB.

I am aware that some of this answers differ from earlier messages from NLB. I came into this project recently, and was not a part of the discussion in the beginning of the project. But now my answers is NLBs answers :-)

**Comment by bertfrees** [comment]
Okay, no problem.

@snaekobbi/expert-group So we'll drop requirement 4.4:76 unless anyone objects. Can somebody help out Kari here regarding the requirement of alternating lines and what should happen with headers/footers in that case? Otherwise we can drop that requirement too. Finally is there anybody who wants line spacing should be configurable on a finer level than document?

**Comment by bertfrees** [comment]
Answering the second part of my question: this requirement is covered by an example from Jens (see https://github.com/snaekobbi/functional-testing/issues/26).

**Comment by bertfrees** [comment]
And I can also answer the third part of my question: MTM needs line spacing to be configurable on section level (see also https://github.com/snaekobbi/functional-testing/issues/26)

**Comment by bertfrees** [comment]
@mixa72 The first example you sent (the one with `brl:class="lz"` and `brl:class="lzlz"`) doesn't belong to the requirement line spacing, but I will use it for requirement [4.4:46](http://dev.pef-format.org/dp2/master/index.xhtml#4.4:46) (margins).

**Comment by mixa72** [comment]
Great, thanks.

Am 28.05.2015 um 18:16 schrieb Bert Frees:
> @mixa72 <https://github.com/mixa72> The first example you
> sent (the one with |brl:class="lz"| and |brl:class="lzlz"|)
> doesn't belong to the requirement line spacing, but I will
> use it for requirement 4.4:46
> <http://dev.pef-format.org/dp2/master/index.xhtml#4.4:46>
> (margins).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snaekobbi/functional-testing/pull/25#issuecomment-106455898>.
>

-- 
Mischa Künzle
Medienverlag
Blindenschrift

SBS Schweizerische Bibliothek für Blinde,
Seh- und Lesebehinderte
Grubenstrasse 12
CH-8045 Zürich
Fon +41 43 333 32 32
Fax +41 43 333 32 33
mailto:mischa.kuenzle@sbs.ch
http://www.sbs.ch

-----
Tag der offenen Tuer - Die SBS mit allen Sinnen erleben
Die SBS laedt Sie herzlich ein: 27. Juni 2015 von 9 bis 16 Uhr. 
Mehr Informationen erhalten Sie unter http://www.sbs.ch/offenetuer

**Comment by bertfrees** [comment]
@paivis I saw in your letter spacing examples (https://github.com/snaekobbi/requirements/issues/2) that for those books you also have double line spacing. But you do it in a way I haven't seen in other examples yet. There are single empty rows between lines of text, but two empty rows between paragraphs. Is that right? In other examples margins are increased proportionally.

We should make this nuance clear in the requirements.

**Comment by dkager** [comment]
>  So we'll drop requirement 4.4:76 unless anyone objects.
While this is not used today there is a use case for this from Dedicon: changing the line spacing to sync the braille and print pages. This works for larger-print books where one or two lines of braille fall off the page. If you decrease the line spacing a bit these lines would still fit and your page numbers stay synchronized.

More granular control is also needed because there are usually more (2-3) empty lines between paragraphs in children's books.

**Comment by bertfrees** [comment]
Celia's requirement made me thinking. The empty lines between paragraphs should probably not be influenced by line spacing. It'll make it easier if that falls entirely under margins. So, your statement is not entirely true. That having said, more granular control wouldn't increase complexity either. By the way we already need control at least on the level of sections, for MTM.

Your use case is very interesting, and rather challenging. Basically what you want is to enable an extra variable, namely the the line squeeze factor, in order to optimize page breaking. This is very common in typesetting, and it's the equivalent of squeezing or stretching words on a line in order to optimize line breaking.

I don't think this fits anywhere in the current requirements though. So maybe create a new issue for it?

**Comment by dkager** [comment]
> I don't think this fits anywhere in the current requirements though. So maybe create a new issue for it?
To be clear: this is a "nice to have", we don't currently do this. So it would be a prio 3 issue. Due to the complexity (i.e. you need information about the print text) I'm wondering if we should put this into the optional features for post-processing editing. I don't see an easy way to automate this unless you mark the ends of print pages (which is also required to show the print page numbers in braille). Then you could calculate the optimal line heights. But again this calculation depends on the size of the top and bottom margins of blocks, and you need a way to specify minimum height, i.e. always at least half a line.

> The empty lines between paragraphs should probably not be influenced by line spacing. It'll make our lives easier if that falls entirely under margins
Agreed. This is true for all block elements.

Another use case for fine-grained control, at least on paragraph level, is not having double line-spacing in the table of contents whereas you do have double lines in the actual text. (How does a section relate to a paragraph? Would the TOC be a section?)

**Comment by bertfrees** [comment]
With sections I mean groups of pages (PEF terminology).

**Comment by bertfrees** [comment]
@snaekobbi/experts Please have a look at http://dev.pef-format.org/dp2/line-spacing/index.xhtml and let me know if you think something w.r.t. requirements for line spacing is not clear enough, something is missing, or if you don't agree with a requirement.

**Comment by KariRudjord** [comment]
When we make books with double line spacing, we keep the title page and the table of content in single line spacing. Do you need an example of that?

**Comment by bertfrees** [comment]
@KariRudjord Sure, if you like. I assume it will be more or less the same as http://dev.pef-format.org/dp2/double-sided/test/double-sided/test.xprocspec.xhtml#75+84, but the more examples the better.

**Pull request closed without merging**
