### PR TITLE
Tests for double-sided printing

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [x] [4.4:75](http://snaekobbi.github.io/requirements#4.4:75)
- [x] [4.5:84](http://snaekobbi.github.io/requirements#4.5:84)
- [x] [4.5:85](http://snaekobbi.github.io/requirements#4.5:85)

Related issues:
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/19
- [ ] https://github.com/snaekobbi/pipeline-mod-braille/issues/27

### CODE REVIEW

**Comment by bertfrees** [comment]
@JC-MTM Thanks got it now!

The test data looks very good. It covers most of what I needed. However [4.5:85](http://dev.pef-format.org/dp2/double-sided/index.xhtml#4.5:85) is not covered yet. An example of this requirement would be that header lines are only put on odd pages. Do you have any requirements like that?

I should also note that your sample is a bit bigger than I expected (35 pages) which makes the test very brittle. A lot of stuff is going on here besides page breaking and line spacing (borders, page numbers, translation, hyphenation) so a lot of things that don't have anything to do with these specific requirements can make the test fail. This is not a major problem but I just wanted to point it out so you can keep it in mind for next times.

**Comment by JC-MTM** [comment]
Hi Bert!
We're currently discussing this requirement (4.5:85). I'll get back to you!

**Comment by JC-MTM** [comment]
Hi! We do not have an example of requirement 4.5.85 at this point.

**Comment by bertfrees** [comment]
Oh. But @BWestling just told me the other day that MTM has this requirement and is currently already using this kind of layout. Right Björn?

Anyway, others can maybe help out if they have the same requirement. @snaekobbi/expert-group: so we're talking about page layout that differs between left and right pages, e.g. page numbers that appear only in the outer corners.

**Comment by dkager** [comment]
Our page numbers always appear topright (and top center for print page numbers).

Van: Bert Frees [mailto:notifications@github.com]
Verzonden: maandag 8 juni 2015 13:05
Aan: snaekobbi/requirements
CC: Davy Kager
Onderwerp: Re: [requirements] Tests for double-sided printing (#26)


Oh. But @BWestling<https://github.com/BWestling> just told me the other day that MTM has this requirement and is currently already using this kind of layout. Right Björn?

Anyway, others can maybe help out if they have the same requirement. @snaekobbi/expert-group<https://github.com/orgs/snaekobbi/teams/expert-group>: so we're talking about page layout that differs between left and right pages, e.g. page numbers that appear only in the outer corners.

—
Reply to this email directly or view it on GitHub<https://github.com/snaekobbi/requirements/pull/26#issuecomment-109951974>.

DISCLAIMER:
De informatie verzonden met dit e-mail bericht is uitsluitend bestemd voor de geadresseerde. Indien u niet de beoogde geadresseerde bent, verzoeken wij u vriendelijk dit aan de afzender te melden (of via: info@dedicon.nl<mailto:info@dedicon.nl>) en het origineel en eventuele kopieën te verwijderen.

The information sent in this e-mail is solely intended for the individual or company to whom it is addressed. If you received this message in error, please notify the sender immediately (or mail to info@dedicon.nl<mailto:info@dedicon.nl>) and delete the original message and possible copies.

**Comment by JC-MTM** [comment]
Maybe i misunderstand what you mean. In the example i sent to you (P54321) there is alternating page numbers, if that is an exemple of the reqiuirement? The even page numbers are on the left hand side of the pages for the braille pagination, the odd page numbers are on the right side of the page.

**Comment by bertfrees** [comment]
Aha! You're right. I hadn't noticed that, but indeed if I set output to ASCII in [the test](http://dev.pef-format.org/dp2/double-sided/test/double-sided/test.xprocspec.xhtml#75+84), it is clear. OK case closed then :)

**Comment by mixa72** [comment]
Hi Bert,

I send you an example of double sided printing where page 
layout differs between left- and right-hand pages. The 
footers only appear on the right hand side and may contain 
the print page number (left) as well as the braille page 
number (right). Besides this layout (very common for fiction 
books), we also have a layout with a footer on every page, 
frequently used for non-fiction books.

Regards,
Mischa

Am 08.06.2015 um 13:05 schrieb Bert Frees:
> Oh. But @BWestling <https://github.com/BWestling> just told
> me the other day that MTM has this requirement and is
> currently already using this kind of layout. Right Björn?
>
> Anyway, others can maybe help out if they have the same
> requirement. @snaekobbi/expert-group
> <https://github.com/orgs/snaekobbi/teams/expert-group>: so
> we're talking about page layout that differs between left
> and right pages, e.g. page numbers that appear only in the
> outer corners.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snaekobbi/requirements/pull/26#issuecomment-109951974>.
>

-- 
Mischa Künzle
Medienverlag
Blindenschrift

SBS Schweizerische Bibliothek für Blinde,
Seh- und Lesebehinderte
Grubenstrasse 12
CH-8045 Zürich
Fon +41 43 333 32 32
Fax +41 43 333 32 33
mailto:mischa.kuenzle@sbs.ch
http://www.sbs.ch


-----
Tag der offenen Tuer - Die SBS mit allen Sinnen erleben
Die SBS laedt Sie herzlich ein: 27. Juni 2015 von 9 bis 16 Uhr. 
Mehr Informationen erhalten Sie unter http://www.sbs.ch/offenetuer
p
          KAPITEL #A
          ----------

   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 _#AA      KAPITEL #A      #A
pBLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
p  BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
 _#AA      KAPITEL #A      #C
p  BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.
   BLA BLA BLA BLA BLA BLA
 BLA BLA BLA BLA BLA BLA BLA
 BLA BLA BLA.




p
p


source code:

<pagenum id="page-11" page="normal">11</pagenum>
<h1>Kapitel 1</h1>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>
<p>bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.</p>

**Comment by bertfrees** [comment]
Thanks Mischa

**Comment by stesk** [comment]
I'm not sure if more input is needed on this matter, but this is definitely a requirement for Nota, as we have footers on recto/odd pages only. Samples available on request.

**Comment by bertfrees** [comment]
I always accept samples. But we already have [this test from Mischa](http://dev.pef-format.org/dp2/double-sided/test/double-sided/test_sbs.xprocspec.xhtml#85). I think it should cover your case, but if it doesn't please do send your sample.

**Comment by stesk** [comment]
It looks exactly right (apart from the contents/layout of the footer, but I'm guessing that's another issue).

**Comment by bertfrees** [comment]
@snaekobbi/experts Please have a look at http://dev.pef-format.org/dp2/double-sided/index.xhtml and let me know if you think something w.r.t. requirements for double sided printing is not clear enough, something is missing, or if you don't agree with a requirement.

**Pull request merged**
