### PR TITLE
Tests for Finnish translation 

### PR DESCRIPTION
**Pull request by bertfrees**
Includes:
- [x] uncontracted braille
- [x] ~~8-dot braille~~
- [ ] emphasis indicators

Addresses requirements:
- [x] [4.3:34](http://snaekobbi.github.io/requirements#4.3:34)
- [x] ~~[4.3:35](http://snaekobbi.github.io/requirements#4.3:35)~~
- [x] [4.3:38](http://snaekobbi.github.io/requirements#4.3:38)
- [ ] [4.3:39](http://snaekobbi.github.io/requirements#4.3:39)

### CODE REVIEW

**Comment by bertfrees** [comment]
As said above there is currently no definition of 8-dot braille. Need to find out whether defining and/or implementing are in scope. If yes, what is the priority.

**Comment by bertfrees** [comment]
@jukkae While you are looking at https://github.com/snaekobbi/pipeline-mod-braille/issues/38 you can maybe also have a look at requirement [4.3:39](http://dev.pef-format.org/dp2/index.xhtml#4.3:39) and check if any tests need to be added for this requirement?

**Comment by bertfrees** [comment]
@jukkae: what do you think, should we cancel requirement 4.3:39?

**Comment by jukkae** [comment]
@bertfrees: I think we don't do anything like that currently and we'll be perfectly happy with just 4.3:38. I think 4.3:39 can be cancelled, but it's probably safest to check with others as well.

**Comment by dkager** [comment]
See also [this comment](https://github.com/snaekobbi/requirements/issues/42#issuecomment-168921714).

**Comment by bertfrees** [comment]
I'm just cancelling it for Finnish for now. There are no tests so we can't implement anything. If others decide to do something like this and you are inspired, you can still do something similar later.

**Pull request closed without merging**
