### PR TITLE
Tests for page layout

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [ ] [4.5:80](http://snaekobbi.github.io/requirements#4.5:80)
- [ ] [4.5:81](http://snaekobbi.github.io/requirements#4.5:81)
- [ ] [4.5:82](http://snaekobbi.github.io/requirements#4.5:82)

Related issues:
- [ ] https://github.com/snaekobbi/functional-testing/issues/29

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks Mischa, good stuff.

**Comment by bertfrees** [comment]
Dear @snaekobbi/experts, Question regarding the following requirements:
- [4.5:80](http://snaekobbi.github.io/requirements#4.5:80): The user shall have control over the page dimensions and the **size of page margins**.
- [4.5:82](http://snaekobbi.github.io/requirements#4.5:82): The header and footer layout shall be able to **change between sections** within the document.
- [4.5:85](http://snaekobbi.github.io/requirements#4.5:85): When printing double-sided, the system shall allow the page layout (**page margins** as well as header and footer layout) to **differ between left- and right-hand** pages.

More specifically I wonder with which granularity page margins need to be controlled. I haven't found any examples of this particular part of the requirements yet.

1. Do we need to be able to set different margins for different sections, or is a document-wide setting enough?
2. When printing double sided, are the inner margins of a sheet always equal, and similarly are the outer margins of a sheet always equal?

**Comment by dkager** [comment]
With regard to 4.5:85:
For books bound by a metal coil we are considering using a narrow left margin on the left-hand page and a wide left margin on the right-hand page. The opposite holds for the right margin. This is done to avoid braille close to the metal coil. Document-level control is good enough. Same for top/bottom margins, which don't alternate for left-hand and right-hand pages.

**Comment by bertfrees** [comment]
@snaekobbi/experts Another question: are there any use cases for having blank lines between the footer and the page content? Like this:

```
text text text
text continues ...

       footer
--------------------
on next page
```

**Comment by mixa72** [comment]
As to 4.5:85: in our fiction books (majority of our production) as well as in some non-fiction books the page layout differs between left- and right-hand pages in that right-hand pages have a footer (whereas left-hand pages don't). However, the page margins are equal (of about 1.5 cm) on both sides, which means a waste of space on the side opposite the metal coil. Therefore, Davy's idea of alternating margins could be an interesting feature for us, too.

**Pull request merged**
