### PR TITLE
Tests for borders

### PR DESCRIPTION
**Pull request by bertfrees**
Addresses requirements:
- [x] [4.4:47](http://dev.pef-format.org/dp2/index.xhtml#4.4:47)
- [x] [4.4:50](http://dev.pef-format.org/dp2/index.xhtml#4.4:50)

### CODE REVIEW

**Comment by bertfrees** [comment]
@mixa72 Do you also have an example for [4.4:50](http://dev.pef-format.org/dp2/borders/index.xhtml#4.4:50)?

**Comment by mixa72** [comment]
No, I guess, I do not have such an example. I am not sure, but I think it does not belong to our requirements. Could you assign that to somebody else? Thanks.

**Comment by bertfrees** [comment]
I was specifically thinking about you when I added that requirement actually :) But maybe I didn't formulate it that well. Isn't [this](http://dev.pef-format.org/dp2/double-sided/test/double-sided/test_sbs.xprocspec.xhtml#85) an example? The border below "Kapitel 1" only reaches as far as the text goes.

**Comment by mixa72** [comment]
Right!!! And I was really wondering and figuring out exotic use cases while things can be that simple (not even Christian could help me out). So, I'll send you some examples with underlining then :-)

**Comment by bertfrees** [comment]
@snaekobbi/experts Please have a look at http://dev.pef-format.org/dp2/borders/index.xhtml and let me know if you think something w.r.t. requirements for borders is not clear enough, something is missing, or if you don't agree with a requirement.

**Comment by dkager** [comment]
Looks good. What sub-requirements are expressed by 47.2 and 47.3? Isn’t the thickness of a border a relative concept, or does the handling of borders change between thin and thick?

Van: Bert Frees [mailto:notifications@github.com]
Verzonden: woensdag 24 juni 2015 21:41
Aan: snaekobbi/requirements
CC: Davy Kager
Onderwerp: Re: [requirements] Tests for borders (#15)


@snaekobbi/experts<https://github.com/orgs/snaekobbi/teams/experts> Please have a look at http://dev.pef-format.org/dp2/borders/index.xhtml and let me know if you think something w.r.t. requirements for borders is not clear enough, something is missing, or if you don't agree with a requirement.

—
Reply to this email directly or view it on GitHub<https://github.com/snaekobbi/requirements/pull/15#issuecomment-114989754>.

DISCLAIMER:
De informatie verzonden met dit e-mail bericht is uitsluitend bestemd voor de geadresseerde. Indien u niet de beoogde geadresseerde bent, verzoeken wij u vriendelijk dit aan de afzender te melden (of via: info@dedicon.nl<mailto:info@dedicon.nl>) en het origineel en eventuele kopieën te verwijderen.

The information sent in this e-mail is solely intended for the individual or company to whom it is addressed. If you received this message in error, please notify the sender immediately (or mail to info@dedicon.nl<mailto:info@dedicon.nl>) and delete the original message and possible copies.

**Comment by bertfrees** [comment]
There's no difference in handling between thin and thick borders, it's just two examples of the same thing. And of course the thickness should be configurable.

**Comment by bertfrees** [comment]
Mischa's 1st and 4th test for 4.4:47 are still failing because the corners of borders can not have a different pattern. In order to support this, we would need new CSS properties called `border-top-left`, `border-top-right`, `border-bottom-right` and `border-bottom-left`.

Test 1 is also failing because the top/bottom border can not be shorter than the contents unless the content is a box with a negative left/right margin. But because the source XML is just a simple sidebar this can not be accomplished. Either the sidebar would have to be wrapped by an element in a preprocessing step, or a new `::outside` pseudo-element could come to rescue.

Test 4 is also failing because the Dotify based formatter doesn't support the '⠒' pattern for border-top and border-bottom.

**Pull request merged**
